module Langs.BasicUntyped (
    ObjDeBr(Integ,Constant,V,X,(:+:),(:*:),Intneg,IntSet,
    -- EmptySet
    Bound,Hilbert),
    PropDeBr(Neg,(:&&:),(:||:),(:->:),(:<->:),(:==:),In,(:<=:),F,Forall,Exists),
    DeBrSe(..),
    PrfStdStepPredDeBr,
    PropErrDeBr,
    PropRuleDeBr,
    PredErrDeBr,
    PredRuleDeBr,
    ZFCRuleDeBr,
    showPropDeBrStepsBase,
    showPropDeBrStepsBaseM,
    -- eX, hX, aX,
    -- multiAx,
    showProp,
    showObj,
    showPropM,
    showObjM,
    -- eXBang,
    -- (./=.),
    builderX,
    nIn,
    -- subset,
    -- strictSubset,
    boundDepthObjDeBr,
    boundDepthPropDeBr,
    -- notSubset,
    -- (.@.),
    -- (.:.),
    -- project,
    objDeBrSubX,
    -- crossProd,
    funcsSet,
    -- (.\/.),
    -- (./\.),
    bigUnion,
    bigIntersection,
    -- roster,
    -- (.\.),
    -- powerSet,
    --emptySet,
    (.<.),
    parseIntSet,
    buildPair,
    tuple,
    parseNatSet,
    propDeBrSubX,
    propDeBrSubXs,
    objDeBrSubXs,
    natSetObj,
    parseSetBuilder,
    parseForallChain,
    objDeBrSwapFreeVarsToX,
    propDeBrSwapFreeVarsToX,
    parseImplication,
    parsePair,
    parseIn,
    -- isSet,
    parseBiconditional,
    isRelationOn
) where


import Langs.Internal.BasicUntyped.Core
import Langs.Internal.BasicUntyped.Shorthands
import Langs.Internal.BasicUntyped.Rendering
import Langs.Internal.BasicUntyped.Axiomizations